[package]
name = "erc-search"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
clap = "3.0.0-beta.4"
ldap3 = "0.9"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
