verbose = false

[sources]

[sources.people]
site = "ldap.eurocontrol.fr"
port = 389
base = "ou=eurousers,o=eurocontrol,o=ec"
filter = "(&(objectclass=eurocontrolperson)(%s=*%s*))"
attrs = [
    "ksn",
    "kgivenname",
    "telephonenumber",
    "eurocontrolroomid",
    "mail",
    "uid",
    "eurocontrolunitcode",
    "eurocontrolgrade",
    "eurocontrolworkstation",
]

[sources.machine]
domain = "sky.corp.eurocontrol.int"
#site = "sspdc001.sky.corp.eurocontrol.int"
port = 3268
base = "DC=sky,DC=corp,DC=eurocontrol,DC=int"
filter = "(%s=*%s*)"
attrs = [
]